language: node_js

node_js:
  - '0.10'
  - '0.11'

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm install
  - bower install
  - gulp test
  - gulp build

deploy:
  provider: heroku
  strategy: api
  all_branches: true
  skip_cleanup: true
  api_key:
    secure: Ke+/a8HgRH0meV9QRCeIoTeXZgW0MKbZ/ZuiHSimSwdNsAeppV9lzDCL+SgcdR7RrQ2d2yo7ogvzdQvWBtfNqUtRNiNDsra3uu+gmuRoAgFccv1hg8MMOLMbQAPQ5167FJHDkU5qRQ2AejCqsHml834fW8JWYRVyx5QAbdYYvrM=
  app: catwalk
  on:
    repo: Wildhoney/Catwalk.js
